-- Granting ownership to the roles as you originally requested
GRANT OWNERSHIP ON USER SVC_CICD TO ROLE SECURITYADMIN;
GRANT OWNERSHIP ON ROLE FUNC_TERRAFORM_ROLE TO ROLE SECURITYADMIN;

-- Granting parent roles to FUNC_TERRAFORM_ROLE
GRANT ROLE SYSADMIN TO ROLE FUNC_TERRAFORM_ROLE;
GRANT ROLE SECURITYADMIN TO ROLE FUNC_TERRAFORM_ROLE;
GRANT ROLE ACCOUNTADMIN TO ROLE FUNC_TERRAFORM_ROLE;
