name: "Terraform Apply"
description: "Apply Terraform changes"
inputs:
  environment:
    required: true
    description: "The name of the Terraform environment config"

runs:
  using: "composite"
  steps:

    - name: Set SOURCE_GIT_BRANCH_NAME Variable
      run: echo "SOURCE_GIT_BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      shell: bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Plan
      run: bash ./src/cicd/scripts/common/terraform_plan.sh ${{ inputs.environment }}
      shell: bash

    - name: Terraform Apply
      run: bash ./src/cicd/scripts/code_deployment_scripts/terraform_apply.sh ${{ inputs.environment }}
      shell: bash

    - name: Push Terraform State File to Git
      run: bash ./src/cicd/scripts/code_deployment_scripts/push_files_to_git/push_files_to_git.sh ${{ env.SOURCE_GIT_BRANCH_NAME }} ${{ inputs.environment }}
      shell: bash
