---
# all commands by default will run on every commit
default_install_hook_types: [pre-commit]
default_stages: [commit]
# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'
repos:
    # Git hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: no-commit-to-branch # prevents users from pushing changes to specific (protected) branches
            args: [--branch, main]
            name: Git checks - prevent pushing to protected branches
    - repo: local
      hooks:
          - id: git_branch_name_validation # Custom Git branch validation hook
            name: Git checks - validate branch name
            description: This hook validates the Git branch name.
            entry: src/sh/pre_commit_hooks/git_validate_branch_name.sh
            language: script
            pass_filenames: false
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict # checks for files that contain merge conflict strings.
            name: Git checks - detect merge conflicts
    # Terraform hooks
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.97.3
      hooks:
          # - id: terraform_tflint
          - id: terraform_fmt
            exclude: (src/templates/.*)
          - id: terraform_validate
            exclude: (src/templates/.*|archive/.*)
    # YAML hooks
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.30.0
      hooks:
          - id: yamllint # Lint YAML files using rules specified in .yamllint
            args: [-c=.yamllint]
            name: YAML checks - YAML linting with yamllint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt # yamlfmt - fix input yaml files
            name: YAML fixes - fix YAML formatting
    # General/housekeeping hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
            name: General fixes - check file endings
          - id: trailing-whitespace # trims trailing whitespace.
            name: General fixes - remove trailing whitespace
          - id: fix-byte-order-marker # removes utf-8 byte order marker.
            name: General fixes - remove UTF-8 byte order marker (BOM)
          - id: mixed-line-ending # replaces or checks mixed line ending.
            name: General fixes - normalise line endings
          - id: check-added-large-files # prevents giant files from being committed.
            name: General checks - check for large files
          - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
            name: General checks - check string case conflicts
          - id: detect-private-key # checks for the existence of private keys.
            name: General checks - detect private keys
    # Shell script validation hook - ensures shell scripts conform to shellcheck
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck # Ensure shell scripts conform to shellcheck
            name: Shell script checks - linter (using shellcheck)
    # - repo: https://github.com/gruntwork-io/pre-commit
    #   rev: v0.1.23
    #   hooks:
    #     - id: tflint
    #       name: Terraform checks - Terraform linting with tflint
    #       args:
    #         - "--call-module-type=all"
    #     - id: terraform-validate
    #       name: Terraform checks - validate Terraform files
    #     - id: terraform-fmt
    #       name: Terraform fixes - format Terraform files
    # - repo: git://github.com/antonbabenko/pre-commit-terraform
    #   rev: v1.92.0
    #   hooks:
    #     - id: terraform_docs
    #       name: Terraform checks - inserts input and output documentation into README.md
    #     - id: terraform_checkov
    #       name: Terraform checks - static analysis of terraform templates to spot potential security issues
