name: "Terraform Validation"
description: "Validates and plans Terraform changes"
inputs:
  environment:
    required: true
    description: "The environment to validate"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Validate and Plan
      run: cd terraform/environments/${{ inputs.environment }} && terraform init && terraform validate && terraform plan
      shell: bash
