name: "Terraform Validate & Plan"
description: "Validates and plans Terraform changes"
inputs:
  environment:
    required: true
    description: "The name of the Terraform environment config"

runs:
  using: "composite"
  steps:

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Validate
      run: bash ./src/cicd/scripts/terraform_validate.sh ${{ inputs.environment }}
      shell: bash

    - name: Terraform Plan
      run: bash ./src/cicd/scripts/common/terraform_plan.sh ${{ inputs.environment }}
      shell: bash
