name: "Terraform Validation"
description: "Validates and plans Terraform changes"
inputs:
  environment:
    required: true
    description: "The environment to validate"

runs:
  using: "composite"
  steps:

    - name: Install Terraform
      run: bash ./src/cicd/scripts/common/install_terraform.sh
      shell: bash

    - name: Terraform Validate
      run: bash ./src/cicd/scripts/terraform_validate.sh ${{ inputs.environment }}
      shell: bash
